apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
spec:
  type: LoadBalancer
  selector:
    app: flask-ml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

